# Generated by Django 5.0.1 on 2024-01-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_genre_alter_movie_year_released'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(to='assessment.genre'),
        ),
    ]
